### PR TITLE
docs: Adds :PutContainerArchive example

### LINKED ISSUE #26: Add ContainerArchive operation
You listed container archive as an experimental Api [here](https://github.com/lispyclouds/contajners/blob/main/doc/002-general-guidelines.md#accessing-undocumentedexperimental-apis), but now in the recent versions I think it is part of the official Api:
https://docs.docker.com/engine/api/v1.44/#tag/Container/operation/ContainerArchive

### PR DESCRIPTION
**Pull request by rafaeldelboni**
Closes #26

### CODE REVIEW

**Comment by lispyclouds** [comment]
Thanks a lot @rafaeldelboni ! Since this is a common use case, can you add this to the end of the common scenarios [section](https://github.com/lispyclouds/contajners/blob/main/doc/002-general-guidelines.md#sample-code-for-common-scenarios)? Also would be nice if you give yourself some credit like [this](https://github.com/lispyclouds/contajners/blob/main/doc/002-general-guidelines.md?plain=1#L91)

**Comment by lispyclouds** [comment]
Could also be worth adding the corresponding GetContainerArchive too I think.

**Comment by rafaeldelboni** [comment]
Something like this?

**Comment by lispyclouds** [comment]
Looks good! Thanks a lot!

**Pull request merged**
